export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'

// ADMIN
export const CURRENT_PAGE_SET = 'CURRENT_PAGE_SET'
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING'
export const AFFILIATES_LOADED = 'AFFILIATES_LOADED'
export const ADMIN_LOADED = 'ADMIN_LOADED'

// PRODUCT
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const PRODUCT_LOADED = 'PRODUCT_LOADED'

// PRODUCT_ADDED
export const SET_CART_DATA = 'SET_CART_DATA'
export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART'
export const CART_LINE_REMOVED = 'CART_LINE_REMOVED'

// COURSE
export const COURSES_LOADED = 'COURSES_LOADED'
export const COURSE_LOADED = 'COURSE_LOADED'