export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED'
export const AFFILIATE_REGISTER_SUCCESS = 'AFFILIATE_REGISTER_SUCCESS'
export const PENDING_AFFILIATE_LOADED = 'PENDING_AFFILIATE_LOADED'
export const UPDATE_AFFILIATE_CONNECTED_ACCOUNT = 'UPDATE_AFFILIATE_CONNECTED_ACCOUNT'

// ADMIN
export const CURRENT_PAGE_SET = 'CURRENT_PAGE_SET'
export const SET_PAGE_LOADING = 'SET_PAGE_LOADING'
export const AFFILIATES_LOADED = 'AFFILIATES_LOADED'
export const AFFILIATE_LOADED = 'AFFILIATE_LOADED'
export const ADMIN_LOADED = 'ADMIN_LOADED'
export const CUSTOMERS_LOADED = 'CUSTOMERS_LOADED'
export const VENDORS_LOADED = 'VENDORS_LOADED'
export const VENDOR_LOADED = 'VENDOR_LOADED'

// PRODUCT
export const PRODUCTS_LOADED = 'PRODUCTS_LOADED'
export const PRODUCT_LOADED = 'PRODUCT_LOADED'

// CATEGORY
export const CATEGORIES_LOADED = 'CATEGORIES_LOADED'
export const CATEGORY_LOADED = 'CATEGORY_LOADED'

// CART
export const SET_CART_DATA = 'SET_CART_DATA'
export const PRODUCT_ADDED_TO_CART = 'PRODUCT_ADDED_TO_CART'
export const CART_LINE_REMOVED = 'CART_LINE_REMOVED'
export const CART_ALL_LINE_REMOVED = 'CART_ALL_LINE_REMOVED'

// COURSE
export const COURSES_LOADED = 'COURSES_LOADED'
export const COURSE_LOADED = 'COURSE_LOADED'

// STRIPE
export const PAYMENT_INTENT_LOADED = 'PAYMENT_INTENT_LOADED'
export const STRIPE_PUBKEY_LOADED = 'STRIPE_PUBKEY_LOADED'

// ORDER
export const ORDERS_LOADED = 'ORDERS_LOADED'
export const ORDER_LOADED = 'ORDER_LOADED'
export const ORDER_ITEMS_LOADED = 'ORDER_ITEMS_LOADED'